export const background = {
  body: '#ffffff',
  // brand: palette.grey['900'],
  // brandAccent,
  // brandAccentActive: brandAccent,
  // brandAccentHover: palette.grey['700'],
  // brandAccentSoft: palette.grey['200'],
  // brandAccentSoftActive: darken(0.025, palette.grey['200']),
  // brandAccentSoftHover: darken(0.05, palette.grey['200']),
  // card: '#ffffff',
  // caution: palette.yellow['500'],
  // cautionLight: palette.yellow['100'],
  // critical: palette.red['600'],
  // criticalActive: darken(0.075, palette.red['600']),
  // criticalHover: darken(0.05, palette.red['600']),
  // criticalLight: palette.red['100'],
  // criticalSoft: palette.red['100'],
  // criticalSoftActive: darken(0.05, palette.red['100']),
  // criticalSoftHover: darken(0.025, palette.red['100']),
  // formAccent,
  // formAccentActive: palette.indigo['700'],
  // formAccentDisabled: palette.grey['200'],
  // formAccentHover: darken(0.05, palette.indigo['600']),
  // formAccentSoft: palette.indigo['100'],
  // formAccentSoftActive: darken(0.05, palette.indigo['100']),
  // formAccentSoftHover: darken(0.025, palette.indigo['100']),
  // info: palette.blue['600'],
  // infoLight: palette.blue['100'],
  // input: '#ffffff',
  // inputDisabled: palette.grey['200'],
  // neutral: palette.grey['200'],
  // neutralLight: palette.grey['100'],
  // positive: palette.mint['600'],
  // positiveLight: palette.mint['100'],
  // promote: palette.purple['600'],
  // promoteLight: palette.purple['100'],
  // selection: palette.grey['100'],
} as const
