export const foreground = {
  // brandAccent,
  // caution: palette.yellow['900'],
  // critical: palette.red['700'],
  // formAccent,
  // info: palette.blue['700'],
  // link,
  // linkHover: link,
  // linkVisited,
  // neutral: black,
  // neutralInverted: white,
  // positive: palette.mint['700'],
  // promote: palette.purple['700'],
  // rating: black,
  // secondary,
  // secondaryInverted: rgba('#fff', 0.65),
} as const
